<a href="https://colab.research.google.com/github/Arka1212/Data-Science-Assignments/blob/main/Pandas_Advance_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Q1. List any five functions of the pandas library with execution.

In [3]:
# Necessary Libraries & Data Loading.
import numpy as np
import pandas as pd

In [4]:
# Mounting Drive.
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
# Loading Sample Dataset.
data = "/content/drive/MyDrive/Dataset/dat (4)/company_sales_data.csv"
df = pd.read_csv(data)
df.head()

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,1,2500,1500,5200,9200,1200,1500,21100,211000
1,2,2630,1200,5100,6100,2100,1200,18330,183300
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600

### 1. Datatype Information

In [6]:
# Information of dataset.
df.info()

# Shows the datatype of all the columns.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   month_number  12 non-null     int64
 1   facecream     12 non-null     int64
 2   facewash      12 non-null     int64
 3   toothpaste    12 non-null     int64
 4   bathingsoap   12 non-null     int64
 5   shampoo       12 non-null     int64
 6   moisturizer   12 non-null     int64
 7   total_units   12 non-null     int64
 8   total_profit  12 non-null     int64
dtypes: int64(9)
memory usage: 992.0 bytes

### 2. Data Description

In [7]:
# Data Description.
df.describe()

# Considers only the numerical values in the dataset.

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.00000,12.000000
mean,6.500000,2873.333333,1542.916667,5825.833333,9500.833333,2117.500000,1542.916667,26027.50000,260275.000000
std,3.605551,584.595172,316.733745,1242.032486,2348.095779,617.724931,316.733745,7014.36594,70143.659404
min,1.000000,1990.000000,1120.000000,4550.000000,6100.000000,1200.000000,1120.000000,18330.00000,183300.000000
25%,3.750000,2460.000000,1305.000000,4862.500000,8015.000000,1795.000000,1305.000000,21065.00000,210650.000000
50%,6.500000,2830.000000,1527.500000,5530.000000,9090.000000,1995.000000,1527.500000,22935.00000,229350.000000
75%,9.250000,3435.000000,1765.000000,6400.000000,10045.000000,2325.000000,1765.000000,29667.50000,296675.000000
max,12.000000,3700.000000,2100.000000,8300.000000,14400.000000,3550.000000,2100.000000,41280.00000,412800.000000

### 3. Dataset Shape

In [8]:
# Dataset Shape.
df.shape

# ROWS = 12 & COLUMNS = 9

(12, 9)

### 4. Column List

In [9]:
# List of all column names.
df.columns

# It lists all the column names in the dataset.

Index(['month_number', 'facecream', 'facewash', 'toothpaste', 'bathingsoap',
       'shampoo', 'moisturizer', 'total_units', 'total_profit'],
      dtype='object')

### 5. Dataset Query

In [10]:
# Querying dataset based on condition.
df.query("total_profit >= 300000")

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
7,8,3700,1400,5860,9960,2860,1400,36140,361400
10,11,2340,2100,7300,13300,2400,2100,41280,412800
11,12,2900,1760,7400,14400,1800,1760,30020,300200

# Q2. Given a Pandas DataFrame df with columns 'A', 'B', and 'C', write a Python function to re-index the DataFrame with a new index that starts from 1 and increments by 2 for each row.

In [11]:
# Python Fucntion to re-index.
def change_index(df):
  '''
  Takes a dataframe and re-indexes the dataframe
  '''
  new_index = range(1, 2 * len(df) + 1, 2)
  new_df = df.set_index(pd.Index(new_index))
  return new_df

In [12]:
# Applying Fucntion to previous dataset.
change_index(df)

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
1,1,2500,1500,5200,9200,1200,1500,21100,211000
3,2,2630,1200,5100,6100,2100,1200,18330,183300
5,3,2140,1340,4550,9550,3550,1340,22470,224700
7,4,3400,1130,5870,8870,1870,1130,22270,222700
9,5,3600,1740,4560,7760,1560,1740,20960,209600
11,6,2760,1555,4890,7490,1890,1555,20140,201400
13,7,2980,1120,4780,8980,1780,1120,29550,295500
15,8,3700,1400,5860,9960,2860,1400,36140,361400
17,9,3540,1780,6100,8100,2100,1780,23400,234000
19,10,1990,1890,8300,10300,2300,1890,26670,266700
21,11,2340,2100,7300,13300,2400,2100,41280,412800
23,12,2900,1760,7400,14400,1800,1760,30020,300200

# Q3. You have a Pandas DataFrame df with a column named 'Values'. Write a Python function that iterates over the DataFrame and calculates the sum of the first three values in the 'Values' column. The function should print the sum to the console.

In [13]:
# Python Function to calculate sum of first three values.
def first_three(c):
  '''
  Takes in a dataset and outputs sum of the first three values in values column.
  '''
  if 'Values' in df.columns:
    v_col = df['Values']

  # Summing up the value.
  val_sum = sum()